# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: scand.westus.cloudapp.azure.com
        username: azureuser
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd scand-100
          git pull
          docker rm -f $(docker ps -aq)
          docker run -p80:80 --name webserver -v /home/azureuser/scand-100/static:/usr/share/nginx/html:ro -d nginx
          
